[build]
builder = "DOCKERFILE"
dockerfile = "Dockerfile"

[deploy]
healthcheck_path = "/"
healthcheck_timeout_sec = 10
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
port = 8080

# You can also specify environment variables if needed
[envs]
PORT = { value = "8080" }
VITE_API_URL = { value = "https://dotnetcrud-production.up.railway.app" } 