[build]
builder = "DOCKERFILE"
dockerfile = "Dockerfile"

[deploy]
healthcheck_path = "/"
healthcheck_timeout_sec = 10
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

# You can also specify environment variables if needed
# [envs]
# VITE_API_URL = { value = "..." } 